# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenSooqTask' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenSooqTask
    pod 'GoogleMaps'
    pod 'Alamofire'
    pod 'Toast-Swift'
    pod 'AlamofireNetworkActivityLogger'
    pod 'Kingfisher'

  target 'OpenSooqTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
